# .github/workflows/publish.yml
name: Build & Publish Summaries

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # <-- allow pushing to branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Build JSON (backend/build_json.py)
        working-directory: backend
        run: |
          mkdir -p public
          python build_json.py
      - name: Publish /backend/public to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: backend/public
